DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 2

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]
  RRCROP_SCALE: (0.4, 1.0) # append by ckx

OPTIM:
  NAME: "sgd"
  LR: 0.00025
  MAX_EPOCH: 50
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 50

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"


TRAINER:
  IIM:
    N_CTX: 16
    CSC: True
    CLASS_TOKEN_POSITION: end